//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StayScape.DesmondsPage {
    
    
    public partial class Register {
        
        protected System.Web.UI.HtmlControls.HtmlForm registerForm;
        
        protected System.Web.UI.WebControls.Panel pnlRegister;
        
        protected System.Web.UI.WebControls.TextBox txtName;
        
        protected System.Web.UI.WebControls.TextBox txtEmail;
        
        protected System.Web.UI.WebControls.TextBox txtPhone;
        
        protected System.Web.UI.WebControls.TextBox txtbDate;
        
        protected System.Web.UI.WebControls.TextBox txtPassword;
        
        protected System.Web.UI.WebControls.TextBox txtPasswordConfirm;
        
        protected System.Web.UI.WebControls.Button btnRegister;
    }
}
